---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: staging-us-east-1
  region: us-east-1
  version: "1.13"

nodeGroups:
  - name: app-v1
    instanceType: m5.large
    desiredCapacity: 3
    privateNetworking: true
    preBootstrapCommands:
      - "yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64bit/session-manager-plugin.rpm"
      - "systemctl enable amazon-ssm-agent"
      - "systemctl start amazon-ssm-agent"
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      withAddonPolicies:
        ImageBuilder: true # allow r/w access to ECR
        ExternalDNS: true
        CertManager: true
        ALBIngress: true
        CloudWatch: true
        EBS: true
